server {
    listen 80;
    server_name 89.169.186.95 foodgram-yulia.duckdns.org;

    server_tokens off;

    # === ReDoc по /api/docs/ ===
    location /api/docs/ {
        alias /usr/share/nginx/html/api/docs/;
        index redoc.html;
    }

    # === медиа ===
    location /media/ {
        alias /media/;
    }

    # === админка Django ===
    location /admin/ {
        proxy_pass http://backend:8000/admin/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # === API Django ===
    location /api/ {
        proxy_pass http://backend:8000/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # короткие ссылки
    location /s/ {
        proxy_pass http://backend:8000/s/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # === статика Django (админка, DRF и т.п.) ===
    location /static/ {
        alias /static/;
    }

    # === фронт (React) ===
    location / {
        alias /static/;
        try_files $uri $uri/ /index.html;
    }
}
