# Generated by Django 5.2.8 on 2025-11-24 19:39

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Время готовки не может быть меньше 1 мин.')], verbose_name='Время готовки (мин)'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='short_link',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Короткая ссылка'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='recipe',
            constraint=models.UniqueConstraint(condition=models.Q(('short_link', ''), _negated=True), fields=('short_link',), name='unique_non_empty_short_link'),
        ),
    ]
