# Generated by Django 5.2.8 on 2025-11-27 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipe_cooking_time_alter_recipe_short_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='short_link',
            field=models.CharField(max_length=255, verbose_name='Короткая ссылка'),
        ),
    ]
